version: "2.0"

#### Services ####
services:

  fluentd:
    build: fluentd
    image: mag3io/fluentd
    ports:
      - '24224:24224'
    links:
      - es:es
    networks:
      - logging
    depends_on:
      - es

  es:
    image: elasticsearch
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - logging

  kibana:
    image: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://es:9200
      - NODE_OPTIONS=--max-old-space-size=300
    networks:
      - logging
    depends_on:
      - es


### Volumes ###
volumes:
  es_data:
    external: 
      name: es_data

### Networks ###
networks:
  logging:
    external:
      name: logging